package Entity;
// Generated Dec 14, 2017 4:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BranchTable generated by hbm2java
 */
public class BranchTable  implements java.io.Serializable {


     private Integer id;
     private int branchId;
     private int status;
     private String name;
     private Date createdAt;
     private int delFlag;

    public BranchTable() {
    }

	
    public BranchTable(int branchId, int status, Date createdAt, int delFlag) {
        this.branchId = branchId;
        this.status = status;
        this.createdAt = createdAt;
        this.delFlag = delFlag;
    }
    public BranchTable(int branchId, int status, String name, Date createdAt, int delFlag) {
       this.branchId = branchId;
       this.status = status;
       this.name = name;
       this.createdAt = createdAt;
       this.delFlag = delFlag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public int getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(int delFlag) {
        this.delFlag = delFlag;
    }




}


