package Entity;
// Generated Dec 14, 2017 4:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderBill generated by hbm2java
 */
public class OrderBill  implements java.io.Serializable {


     private Integer id;
     private int customerId;
     private int branchId;
     private int status;
     private int orderType;
     private double sumMoney;
     private Date createdAt;
     private int delFlag;

    public OrderBill() {
    }

    public OrderBill(int customerId, int branchId, int status, int orderType, double sumMoney, Date createdAt, int delFlag) {
       this.customerId = customerId;
       this.branchId = branchId;
       this.status = status;
       this.orderType = orderType;
       this.sumMoney = sumMoney;
       this.createdAt = createdAt;
       this.delFlag = delFlag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public int getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }
    public double getSumMoney() {
        return this.sumMoney;
    }
    
    public void setSumMoney(double sumMoney) {
        this.sumMoney = sumMoney;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public int getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(int delFlag) {
        this.delFlag = delFlag;
    }




}


