package Entity;
// Generated Dec 14, 2017 4:30:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer id;
     private int orderId;
     private int dishId;
     private int quanlity;
     private double price;
     private Date createdAt;
     private int delFlag;

    public OrderDetail() {
    }

    public OrderDetail(int orderId, int dishId, int quanlity, double price, Date createdAt, int delFlag) {
       this.orderId = orderId;
       this.dishId = dishId;
       this.quanlity = quanlity;
       this.price = price;
       this.createdAt = createdAt;
       this.delFlag = delFlag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getDishId() {
        return this.dishId;
    }
    
    public void setDishId(int dishId) {
        this.dishId = dishId;
    }
    public int getQuanlity() {
        return this.quanlity;
    }
    
    public void setQuanlity(int quanlity) {
        this.quanlity = quanlity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public int getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(int delFlag) {
        this.delFlag = delFlag;
    }




}


